//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "LuminodiodesInterop.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_LuminodiodesInterop_LuminodiodesInterop_LuminodiodesInterop::OneWireSendLuminodiodes___STATIC__VOID__SZARRAY_U1__U4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_LuminodiodesInterop =
{
    "LuminodiodesInterop",
    0x1DE45CC8,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
