//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef LUMINODIODESINTEROP_H
#define LUMINODIODESINTEROP_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

struct Library_LuminodiodesInterop_LuminodiodesInterop_LuminodiodesInterop
{
    NANOCLR_NATIVE_DECLARE(OneWireSendLuminodiodes___STATIC__VOID__SZARRAY_U1__U4);

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_LuminodiodesInterop;

#endif // LUMINODIODESINTEROP_H
