//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "LuminodiodesInterop.h"
#include "LuminodiodesInterop_LuminodiodesInterop_LuminodiodesInterop.h"

using namespace LuminodiodesInterop::LuminodiodesInterop;


HRESULT Library_LuminodiodesInterop_LuminodiodesInterop_LuminodiodesInterop::OneWireSendLuminodiodes___STATIC__VOID__SZARRAY_U1__U4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        CLR_RT_TypedArray_UINT8 param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_UINT8_ARRAY( stack, 0, param0 ) );

        unsigned int param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_UINT32( stack, 1, param1 ) );

        LuminodiodesInterop::OneWireSendLuminodiodes( param0, param1, hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}
