//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef PROJECTESP32_H
#define PROJECTESP32_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

typedef enum __nfpack Program_Instruction
{
    Program_Instruction_Rotate = 0,
    Program_Instruction_Accelate = 1,
    Program_Instruction_HeatUp = 2,
    Program_Instruction_CoolDown = 3,
    Program_Instruction_Illuminate = 4,
    Program_Instruction_Vibrate = 6,
    Program_Instruction_Smoke = 7,
    Program_Instruction_ButtonPress0 = 8,
    Program_Instruction_ButtonPress1 = 9,
    Program_Instruction_ButtonPress2 = 10,
    Program_Instruction_ButtonPress3 = 11,
    Program_Instruction_ButtonPress4 = 12,
    Program_Instruction_ButtonPress5 = 13,
    Program_Instruction_ButtonPress6 = 14,
    Program_Instruction_ButtonPress7 = 15,
    Program_Instruction_ButtonPress8 = 16,
    Program_Instruction_Empty = 255,
} Program_Instruction;

struct Library_ProjectEsp32_ProjectESP32_Network
{
    static const int FIELD_STATIC__<s_mqtt>k__BackingField = 0;
    static const int FIELD_STATIC__<GotInstructions>k__BackingField = 1;

    //--//
};

struct Library_ProjectEsp32_ProjectESP32_Network__<>c
{
    static const int FIELD_STATIC__<>9 = 2;
    static const int FIELD_STATIC__<>9__8_0 = 3;

    //--//
};

struct Library_ProjectEsp32_ProjectESP32_Periphery
{
    static const int FIELD_STATIC__<s_gpioController>k__BackingField = 4;
    static const int FIELD_STATIC__<s_keyMatrix>k__BackingField = 5;
    static const int FIELD_STATIC__<s_display>k__BackingField = 6;
    static const int FIELD_STATIC__<s_tmp112>k__BackingField = 7;
    static const int FIELD_STATIC__<s_lsm6>k__BackingField = 8;
    static const int FIELD_STATIC__<s_checkingTemperature>k__BackingField = 9;
    static const int FIELD_STATIC__<s_checkingRotation>k__BackingField = 10;
    static const int FIELD_STATIC__<s_checkingAccelation>k__BackingField = 11;
    static const int FIELD_STATIC__<Action>k__BackingField = 12;

    NANOCLR_NATIVE_DECLARE(OneWireSendLuminodiodes___STATIC__VOID__SZARRAY_U1);

    //--//
};

struct Library_ProjectEsp32_ProjectESP32_Program
{
    static const int FIELD_STATIC__<_instructions>k__BackingField = 13;

    //--//
};

struct Library_ProjectEsp32_ProjectESP32_Periphery__<>c
{
    static const int FIELD_STATIC__<>9 = 14;
    static const int FIELD_STATIC__<>9__44_0 = 15;
    static const int FIELD_STATIC__<>9__44_1 = 16;
    static const int FIELD_STATIC__<>9__44_2 = 17;
    static const int FIELD_STATIC__<>9__44_3 = 18;

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_ProjectEsp32;

#endif // PROJECTESP32_H
