//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef PROJECT_ESP32_H
#define PROJECT_ESP32_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

struct Library_project_esp32_DataNS_Data
{
    static const int FIELD__Buttons = 1;
    static const int FIELD__Rotation = 2;
    static const int FIELD__Accelation = 3;
    static const int FIELD__Temperature = 4;
    static const int FIELD__PhotoSensor = 5;
    static const int FIELD__GasSensor = 6;
    static const int FIELD__VibrationSensor = 7;

    //--//
};

struct Library_project_esp32_PeripheryNS_PeripheryController
{
    static const int FIELD_STATIC__GpioController = 0;

    static const int FIELD___buttons = 1;
    static const int FIELD___photoSensor = 2;
    static const int FIELD___vibrationSensor = 3;
    static const int FIELD___gasSensor = 4;
    static const int FIELD___tmp112 = 5;
    static const int FIELD___lsm6 = 6;
    static const int FIELD___vibrationMotor = 7;
    static const int FIELD___door = 8;

    //--//
};

struct Library_project_esp32_PeripheryNS_PeripheryController__Actuators__Luminodiodes
{
    static const int FIELD__<PinNumber>k__BackingField = 1;

    NANOCLR_NATIVE_DECLARE(NativeGetHardwareSerial___STATIC__VOID__SZARRAY_U1);

    //--//
};

struct Library_project_esp32_PeripheryNS_PeripheryController__Actuators__Mechanical
{
    static const int FIELD__<PinNumber>k__BackingField = 1;

    //--//
};

struct Library_project_esp32_PeripheryNS_PeripheryController__Constants__Pins
{
    static const int FIELD_STATIC__Buttons = 1;

    //--//
};

struct Library_project_esp32_PeripheryNS_PeripheryController__SimpleSensors__Sensor
{
    static const int FIELD__<PinNumber>k__BackingField = 1;

    //--//
};

struct Library_project_esp32_project_esp32_Program
{
    static const int FIELD___peripheryController = 1;
    static const int FIELD___networkController = 2;

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_project_esp32;

#endif // PROJECT_ESP32_H
