//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "NF_OneWire.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_NF_OneWire_NF_OneWire_YF923::SendImage___STATIC__VOID__SZARRAY_U1__U4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NF_OneWire =
{
    "NF.OneWire",
    0xCDA96031,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
