//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef NF_ONEWIRE_H
#define NF_ONEWIRE_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

struct Library_NF_OneWire_NF_OneWire_YF923
{
    NANOCLR_NATIVE_DECLARE(SendImage___STATIC__VOID__SZARRAY_U1__U4);

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NF_OneWire;

#endif // NF_ONEWIRE_H
